export const islamicBooks = [
  {
    id: 'ghazali-tahafut',
    title_en: 'Tahafut al-Falasifa (Incoherence of the Philosophers)',
    title_ur: 'تہافۃ الفلاسفہ',
    title_hi: 'तहाफ़ुत अल-फ़लासिफ़ा (दार्शनिकों की असंगतता)',
    title_ar: 'تهافت الفلاسفة',
    author_en: 'Imam Abu Hamid al-Ghazali (Hujjat al-Islam)',
    author_ur: 'امام ابو حامد الغزالی',
    author_hi: 'इमाम अबू हामिद अल-ग़ज़ाली',
    author_ar: 'الإمام أبو حامد الغزالي',
    category: 'philosophy-kalam',
    era: 'Classical Golden Age (11th Century / 5th AH)',
    hijri_year: '488 AH',
    year: '1095',
    language: 'Arabic / Urdu / English',
    publisher: 'Dar al-Ma\'arif / Islamic Research Institute',
    pages: 348,
    description: 'इस्लामी दर्शन और तर्कशास्त्र का ऐतिहासिक महाग्रंथ, जिसमें इमाम ग़ज़ाली ने नव-प्लेटोवादी और अरस्तूवादी दार्शनिकों के सिद्धांतों की गहरी तार्किक समालोचना प्रस्तुत की है।',
    description_en: 'Landmark philosophical masterpiece by Al-Ghazali critically examining Aristotelian and Avicennian metaphysics, causation, and rational theology.',
    downloads_count: 24800,
    views_count: 89400,
    is_featured: true,
    file_name: 'tahafut-al-falasifa.pdf',
    cover_bg: '#0a192f',
    cover_color: '#1d4ed8',
    accent_color: '#d4af37',
    tag: 'दर्शन व कलाम'
  },
  {
    id: 'iqbal-reconstruction',
    title_en: 'The Reconstruction of Religious Thought in Islam',
    title_ur: 'تشکیلِ جدید الہیاتِ اسلامیہ',
    title_hi: 'द रिकंस्ट्रक्शन ऑफ़ रिलिजियस थॉट इन इस्लाम',
    title_ar: 'تجديد الفكر الديني في الإسلام',
    author_en: 'Allama Muhammad Iqbal',
    author_ur: 'علامہ محمد اقبال',
    author_hi: 'अल्लामा मुहम्मद इक़बाल',
    author_ar: 'الدكتور محمد إقبال',
    category: 'modern-discourse',
    era: 'Modern Era (20th Century / 14th AH)',
    hijri_year: '1349 AH',
    year: '1930',
    language: 'English / Urdu / Hindi',
    publisher: 'Oxford University Press / Iqbal Academy',
    pages: 236,
    description: 'आधुनिक इस्लामी पुनर्जागरण और दर्शन का सर्वोच्च ग्रंथ। इक़बाल ने कुरआन के सिद्धांतों को आधुनिक विज्ञान, कांट, बर्गसां और आइंस्टीन के सिद्धांतों के आलोक में प्रस्तुत किया।',
    description_en: 'Seminal modern philosophical work reconciling classical Islamic epistemology and metaphysics with contemporary Western scientific thought and Bergsonian duration.',
    downloads_count: 31200,
    views_count: 104500,
    is_featured: true,
    file_name: 'reconstruction-religious-thought.pdf',
    cover_bg: '#1e050d',
    cover_color: '#9f1239',
    accent_color: '#fbbf24',
    tag: 'आधुनिक विमर्श'
  },
  {
    id: 'ibn-arabi-fusus',
    title_en: 'Fusus al-Hikam (The Ringstones of Wisdom)',
    title_ur: 'فصوص الحکم',
    title_hi: 'फ़ुसूस अल-हिकम (प्रज्ञा के रत्न)',
    title_ar: 'فصوص الحكم',
    author_en: 'Shaykh al-Akbar Ibn Arabi',
    author_ur: 'الشیخ الاکبر محی الدین ابن عربی',
    author_hi: 'शैख़ अल-अकबर इब्न अरबी',
    author_ar: 'الشيخ الأكبر محيي الدين بن عربي',
    category: 'sufism-tasawwuf',
    era: 'Andalusian Golden Age (13th Century / 7th AH)',
    hijri_year: '627 AH',
    year: '1229',
    language: 'Arabic / Urdu / English',
    publisher: 'Dar Sadir, Beirut / Hikmah Preservation Archive',
    pages: 412,
    description: 'सूफी तत्वमीमांसा (वहदत अल-वुजूद) का शिखर ग्रंथ। 27 पैगंबरों के आध्यात्मिक प्रतीकवाद और ईश्वरीय ज्ञान का अगाध विश्लेषण।',
    description_en: 'The pinnacle of Islamic mystical ontology expounding Wahdat al-Wujud (Unity of Being) through the spiritual wisdom of twenty-seven Prophets.',
    downloads_count: 19800,
    views_count: 76200,
    is_featured: true,
    file_name: 'fusus-al-hikam.pdf',
    cover_bg: '#140524',
    cover_color: '#7e22ce',
    accent_color: '#e9d5ff',
    tag: 'तसव्वुफ़ व दर्शन'
  },
  {
    id: 'ibn-khaldun-muqaddimah',
    title_en: 'The Muqaddimah (An Introduction to History)',
    title_ur: 'مقدمۂ ابن خلدون',
    title_hi: 'मुक़द्दिमा (इतिहास व समाजशास्त्र की प्रस्तावना)',
    title_ar: 'مقدمة ابن خلدون',
    author_en: 'Ibn Khaldun (Father of Historiography)',
    author_ur: 'عبد الرحمن ابن خلدون',
    author_hi: 'अब्दुर्रहमान इब्न ख़लदून',
    author_ar: 'عبد الرحمن بن خلدون الحضرمي',
    category: 'history-civilization',
    era: 'Classical Era (14th Century / 8th AH)',
    hijri_year: '779 AH',
    year: '1377',
    language: 'Arabic / Urdu / English',
    publisher: 'Bulaq Press / Princeton University Press Edition',
    pages: 680,
    description: 'विश्व इतिहास, समाजशास्त्र (उमरानियात), सामाजिक एकजुटता (असबिया) और सभ्यताओं के उत्थान-पतन का अमर वैज्ञानिक सिद्धांत।',
    description_en: 'Universal monument of social science, introducing sociology (Ilm al-Umran), social cohesion (Asabiyyah), and the cyclical nature of civilizations.',
    downloads_count: 28900,
    views_count: 98100,
    is_featured: true,
    file_name: 'ibn-khaldun-muqaddimah.pdf',
    cover_bg: '#240d04',
    cover_color: '#c2410c',
    accent_color: '#fed7aa',
    tag: 'सभ्यता व इतिहास'
  },
  {
    id: 'shah-waliullah-hujjat',
    title_en: 'Hujjat Allah al-Baligha (The Conclusive Argument from God)',
    title_ur: 'حجۃ اللہ البالغہ',
    title_hi: 'हुज्जत अल्लाह अल-बालिगा',
    title_ar: 'حجة الله البالغة',
    author_en: 'Shah Waliullah Dehlawi',
    author_ur: 'شاہ ولی اللہ محدث دہلوی',
    author_hi: 'शाह वलीउल्लाह मुहद्दिस देहलवी',
    author_ar: 'الإمام أحمد شاه ولي الله الدهلوي',
    category: 'philosophy-kalam',
    era: 'Early Modern (18th Century / 12th AH)',
    hijri_year: '1150 AH',
    year: '1737',
    language: 'Arabic / Urdu / English',
    publisher: 'Matba-e-Siddiqi, Delhi / Islamic Research Academy',
    pages: 560,
    description: 'शरिया के आदेशों का तार्किक व दार्शनिक औचित्य (हिकमत-ए-शरीअत), सामाजिक सुधार और नैतिक व्यवस्था का कालजयी ग्रंथ।',
    description_en: 'Masterpiece of philosophical theology synthesizing social sciences, ethics, and the wisdom underlying Divine law (Hikmat al-Tashri).',
    downloads_count: 21500,
    views_count: 73400,
    is_featured: true,
    file_name: 'hujjat-allah-al-baligha.pdf',
    cover_bg: '#051f18',
    cover_color: '#047857',
    accent_color: '#6ee7b7',
    tag: 'कलाम व हिकमत'
  },
  {
    id: 'ibn-kathir-tafsir',
    title_en: 'Tafsir al-Quran al-Azim (Ibn Kathir)',
    title_ur: 'تفسیر ابن کثیر',
    title_hi: 'तफ़्सीर इब्न कसीर (कुरआन की महान व्याख्या)',
    title_ar: 'تفسير القرآن العظيم لابن كثير',
    author_en: 'Al-Hafiz Imad ad-Din Ibn Kathir',
    author_ur: 'حافظ عماد الدین ابن کثیر',
    author_hi: 'हाफ़िज़ इमादुद्दीन इब्न कसीर',
    author_ar: 'الحافظ إسماعيل بن كثير القرشي',
    category: 'quran-tafsir',
    era: 'Classical Era (14th Century / 8th AH)',
    hijri_year: '774 AH',
    year: '1370',
    language: 'Arabic / Urdu / Hindi',
    publisher: 'Dar Taybah / Maktaba-e-Farooqi',
    pages: 720,
    description: 'कुरआन की व्याख्या का सबसे प्रामाणिक व व्यापक ऐतिहासिक भाष्य (तफ़्सीर बिल-मअसूर), जो साक्ष्य और हदीस विश्लेषण पर आधारित है।',
    description_en: 'The definitive classical traditional commentary on the Holy Quran, renowned for its rigorous textual cross-referencing and Hadith methodology.',
    downloads_count: 36400,
    views_count: 128000,
    is_featured: true,
    file_name: 'tafsir-ibn-kathir.pdf',
    cover_bg: '#1f1402',
    cover_color: '#b45309',
    accent_color: '#fde68a',
    tag: 'कुरआन व तफ़्सीर'
  },
  {
    id: 'ibn-sina-kitab-al-shifa',
    title_en: 'Kitab al-Shifa (The Book of Healing - Metaphysics)',
    title_ur: 'کتاب الشفاء (الاہیات و فلسفہ)',
    title_hi: 'किताब अल-शिफ़ा (तत्वमीमांसा व दर्शन)',
    title_ar: 'كتاب الشفاء - الإلهيات',
    author_en: 'Ibn Sina (Avicenna - Prince of Physicians)',
    author_ur: 'ابو علی حسین ابن سینا',
    author_hi: 'अबू अली हुसैन इब्न सीना (एविसेना)',
    author_ar: 'الشيخ الرئيس أبو علي بن سينا',
    category: 'philosophy-kalam',
    era: 'Classical Islamic Golden Age (11th Century / 5th AH)',
    hijri_year: '418 AH',
    year: '1027',
    language: 'Arabic / English / Urdu',
    publisher: 'Cairo University Academy of Arabic Language',
    pages: 490,
    description: 'इब्न सीना का दार्शनिक विश्वकोश जिसमें तर्कशास्त्र, भौतिकी, गणित और तत्वमीमांसा के गहन सिद्धांत संकलित हैं।',
    description_en: 'Monumental philosophical encyclopedia by Avicenna covering logic, metaphysics, cosmology, and rational epistemology that shaped world philosophy.',
    downloads_count: 18400,
    views_count: 67200,
    is_featured: false,
    file_name: 'kitab-al-shifa-ibn-sina.pdf',
    cover_bg: '#07152b',
    cover_color: '#1d4ed8',
    accent_color: '#93c5fd',
    tag: 'शास्त्रीय दर्शन'
  },
  {
    id: 'syed-ameer-ali-spirit-of-islam',
    title_en: 'The Spirit of Islam: A History of Evolution and Ideals',
    title_ur: 'روحِ اسلام',
    title_hi: 'द स्पिरिट ऑफ़ इस्लाम (इस्लाम की चेतना)',
    title_ar: 'روح الإسلام وتاريخ تطوره',
    author_en: 'Syed Ameer Ali',
    author_ur: 'سید امیر علی',
    author_hi: 'सैयद अमीर अली',
    author_ar: 'سيد أمير علي',
    category: 'history-civilization',
    era: 'Modern Era (19th-20th Century / 13th-14th AH)',
    hijri_year: '1308 AH',
    year: '1891',
    language: 'English / Urdu / Hindi',
    publisher: 'Christophers, London / Islamic Heritage Trust',
    pages: 480,
    description: 'आधुनिक विश्व में इस्लामी सभ्यता, वैज्ञानिक उन्नति, महिलाओं के अधिकार और मानवीय दर्शन की ऐतिहासिक व तर्कसंगत प्रस्तुति।',
    description_en: 'A profound exposition of Islamic civilizational achievements, progressive legal philosophy, human rights, and social evolution.',
    downloads_count: 16700,
    views_count: 59300,
    is_featured: true,
    file_name: 'spirit-of-islam-ameer-ali.pdf',
    cover_bg: '#1f0d06',
    cover_color: '#c2410c',
    accent_color: '#fbcfe8',
    tag: 'सभ्यता व विमर्श'
  },
  {
    id: 'ibn-rushd-fasl-al-maqal',
    title_en: 'Fasl al-Maqal (The Decisive Treatise on Reason and Faith)',
    title_ur: 'فصل المقال فیما بین الحکمۃ والشریعۃ من الاتصال',
    title_hi: 'फ़स्ल अल-मक़ाल (तर्क और आस्था का सामंजस्य)',
    title_ar: 'فصل المقال فيما بين الحكمة والشريعة من الاتصال',
    author_en: 'Ibn Rushd (Averroes)',
    author_ur: 'ابو الولید محمد ابن رشد قرطبی',
    author_hi: 'इब्न रुश्द (एवरोज़)',
    author_ar: 'أبو الوليد محمد بن أحمد بن رشد',
    category: 'philosophy-kalam',
    era: 'Andalusian Golden Age (12th Century / 6th AH)',
    hijri_year: '575 AH',
    year: '1179',
    language: 'Arabic / Urdu / English',
    publisher: 'Dar al-Afaq al-Jadida, Casablanca',
    pages: 180,
    description: 'दार्शनिक विवेक और धार्मिक आस्था के मध्य सामंजस्य का निर्णायक ग्रंथ। इब्न रुश्द ने प्रमाणित किया कि दर्शन का अध्ययन धार्मिक कर्तव्य है।',
    description_en: 'The decisive treatise establishing that the study of philosophy and rational inquiry is not only permissible but an intellectual obligation in Islam.',
    downloads_count: 22100,
    views_count: 81500,
    is_featured: true,
    file_name: 'fasl-al-maqal-ibn-rushd.pdf',
    cover_bg: '#041829',
    cover_color: '#1d4ed8',
    accent_color: '#60a5fa',
    tag: 'तर्क व आस्था'
  },
  {
    id: 'shibli-maarif-journal',
    title_en: 'Ma\'arif Islamic Research Journal (Centenary Golden Volume)',
    title_ur: 'ماہنامہ معارف اعظم گڑھ (خصوصی علمی و تحقیقی جلد)',
    title_hi: 'मआरिफ़ इस्लामी शोध पत्रिका (शताब्दी विशेषांक)',
    title_ar: 'مجلة المعارف للدراسات الإسلامية والبحوث التاريخية',
    author_en: 'Darul Musannefin Shibli Academy',
    author_ur: 'دار المصنفین شبلی اکیڈمی',
    author_hi: 'दारुल मुसन्निफ़ीन शिब्ली एकेडमी',
    author_ar: 'دار المصنفين أكاديمية شبلي',
    category: 'periodicals-journals',
    era: 'Academic Era (20th Century / 14th AH)',
    hijri_year: '1335 AH',
    year: '1916',
    language: 'Urdu / Arabic / English',
    publisher: 'Shibli Academy Press, Azamgarh',
    pages: 280,
    description: 'उपमहाद्वीप की प्रतिष्ठित इस्लामी शोध पत्रिका, जिसमें इतिहास, कलाम, साहित्य और आधुनिक विमर्श पर ऐतिहासिक शोधपत्र संगृहीत हैं।',
    description_en: 'Premier peer-reviewed Islamic intellectual journal documenting century-long research in historiography, philosophy, and oriental scholarship.',
    downloads_count: 14200,
    views_count: 48900,
    is_featured: true,
    file_name: 'maarif-shibli-academy-journal.pdf',
    cover_bg: '#0c1a29',
    cover_color: '#334155',
    accent_color: '#94a3b8',
    tag: 'शोध पत्रिका'
  },
  {
    id: 'imam-malik-muwatta',
    title_en: 'Al-Muwatta (The Approved Compendium of Traditions & Law)',
    title_ur: 'موطأ امام مالک',
    title_hi: 'मुवत्ता इमाम मालिक (हदीस व न्यायशास्त्र)',
    title_ar: 'الموطأ للإمام مالك بن أنس',
    author_en: 'Imam Malik ibn Anas (Imam Dar al-Hijrah)',
    author_ur: 'امام مالک بن انس',
    author_hi: 'इमाम मालिक इब्न अनस',
    author_ar: 'الإمام مالك بن أنس الأصبحي',
    category: 'hadith-sunnah',
    era: 'Early Classical Era (8th Century / 2nd AH)',
    hijri_year: '150 AH',
    year: '768',
    language: 'Arabic / Urdu / English',
    publisher: 'Dar al-Gharb al-Islami / Medina Classical Press',
    pages: 520,
    description: 'हदीस और मदीना के विधिक न्यायशास्त्र का प्रथम व्यवस्थित ऐतिहासिक संकलन।',
    description_en: 'The earliest surviving codified compendium of Prophetic Hadith and living legal praxis of Medina.',
    downloads_count: 27100,
    views_count: 94000,
    is_featured: true,
    file_name: 'muwatta-imam-malik.pdf',
    cover_bg: '#031f17',
    cover_color: '#047857',
    accent_color: '#a7f3d0',
    tag: 'हदीस व सुन्नत'
  },
  {
    id: 'qushayri-risala',
    title_en: 'Al-Risala al-Qushayriyya (Principles of Islamic Mysticism)',
    title_ur: 'الرسالۃ القشیریۃ فی علم التصوف',
    title_hi: 'अर-रिसाला अल-क़ुशैरिया (तसव्वुफ़ के मूल सिद्धांत)',
    title_ar: 'الرسالة القشيرية في علم التصوف',
    author_en: 'Imam Abu al-Qasim al-Qushayri',
    author_ur: 'امام ابو القاسم عبد الکریم القشیری',
    author_hi: 'इमाम अबुल क़ासिम अल-क़ुशायरी',
    author_ar: 'الإمام أبو القاسم عبد الكريم القشيري',
    category: 'sufism-tasawwuf',
    era: 'Classical Era (11th Century / 5th AH)',
    hijri_year: '437 AH',
    year: '1045',
    language: 'Arabic / Urdu / English',
    publisher: 'Dar al-Kutub al-Ilmiyyah, Cairo',
    pages: 390,
    description: 'तसव्वुफ़ का सबसे प्रामाणिक ग्रंथ, जो सूफी शब्दावली, आध्यात्मिक अवस्थाओं (अहवाल व मक़ामात) और पवित्र आचरण को शरिया के साथ जोड़ता है।',
    description_en: 'The foundational manual of orthodox Islamic mysticism systematically explaining spiritual states, stations, and ascetic ethics.',
    downloads_count: 15300,
    views_count: 52100,
    is_featured: false,
    file_name: 'al-risala-al-qushayriyya.pdf',
    cover_bg: '#1c082e',
    cover_color: '#7e22ce',
    accent_color: '#d8b4fe',
    tag: 'तसव्वुफ़ व आत्मज्ञान'
  },
  {
    id: 'fazlur-rahman-islam-modernity',
    title_en: 'Islam and Modernity: Transformation of an Intellectual Tradition',
    title_ur: 'اسلام اور جدیدیت: فکری روایت کی تبدیلی',
    title_hi: 'इस्लाम और आधुनिकता: एक बौद्धिक परंपरा का रूपांतरण',
    title_ar: 'الإسلام والحداثة: تحول التراث الفكري',
    author_en: 'Prof. Fazlur Rahman (University of Chicago)',
    author_ur: 'پروفیسر فضل الرحمٰن',
    author_hi: 'प्रो. फ़ज़लुर रहमान',
    author_ar: 'الدكتور فضل الرحمن',
    category: 'modern-discourse',
    era: 'Contemporary Era (20th Century / 14th AH)',
    hijri_year: '1402 AH',
    year: '1982',
    language: 'English / Urdu / Hindi',
    publisher: 'University of Chicago Press / Islamic Publications',
    pages: 220,
    description: 'आधुनिक इस्लामी शिक्षा, हर्मिन्यूटिक्स (व्याख्या विज्ञान) और बौद्धिक पुनरुत्थान पर गहन दार्शनिक विश्लेषण।',
    description_en: 'Seminal hermeneutical work proposing a double-movement theory of Quranic interpretation to address contemporary moral and intellectual dilemmas.',
    downloads_count: 13900,
    views_count: 46700,
    is_featured: false,
    file_name: 'islam-and-modernity-fazlur-rahman.pdf',
    cover_bg: '#240612',
    cover_color: '#9f1239',
    accent_color: '#fda4af',
    tag: 'समकालीन विमर्श'
  },
  {
    id: 'shahrastani-milal',
    title_en: 'Kitab al-Milal wa al-Nihal (Religions, Sects and Philosophical Schools)',
    title_ur: 'کتاب الملل والنحل',
    title_hi: 'किताब अल-मिलल वन-निहल (विश्व धर्म व दर्शन)',
    title_ar: 'كتاب الملل والنحل للشهرستاني',
    author_en: 'Muhammad al-Shahrastani',
    author_ur: 'محمد بن عبد الکریم الشہرستانی',
    author_hi: 'मुहम्मद इब्न अब्दुल करीम अल-शहरस्तानी',
    author_ar: 'أبو الفتح محمد بن عبد الكريم الشهرستاني',
    category: 'philosophy-kalam',
    era: 'Classical Era (12th Century / 6th AH)',
    hijri_year: '521 AH',
    year: '1127',
    language: 'Arabic / Urdu / English',
    publisher: 'Dar al-Fikr, Beirut',
    pages: 450,
    description: 'विश्व में तुलनात्मक धर्म और दर्शन का पहला वस्तुनिष्ठ विश्वकोश, जिसमें प्राचीन ग्रीक, भारतीय, यहूदी, ईसाई और इस्लामी दर्शन का विवरण है।',
    description_en: 'The world\'s first systematic encyclopedia of comparative religion, theological sects, and philosophical schools.',
    downloads_count: 17800,
    views_count: 61400,
    is_featured: false,
    file_name: 'kitab-al-milal-wa-al-nihal.pdf',
    cover_bg: '#04192b',
    cover_color: '#1d4ed8',
    accent_color: '#bae6fd',
    tag: 'तुलनात्मक धर्म व दर्शन'
  },
  {
    id: 'ghazali-mishkat-al-anwar',
    title_en: 'Mishkat al-Anwar (The Niche for Lights)',
    title_ur: 'مشکوٰۃ الانوار',
    title_hi: 'मिश्कात अल-अनवार (प्रकाश का आला)',
    title_ar: 'مشكاة الأنوار للغزالي',
    author_en: 'Imam Abu Hamid al-Ghazali',
    author_ur: 'امام ابو حامد الغزالی',
    author_hi: 'इमाम अबू हामिद अल-ग़ज़ाली',
    author_ar: 'الإمام أبو حامد الغزالي',
    category: 'sufism-tasawwuf',
    era: 'Classical Era (11th Century / 5th AH)',
    hijri_year: '499 AH',
    year: '1105',
    language: 'Arabic / Urdu / English',
    publisher: 'Maktaba-e-Ilmiyyah, Damascus',
    pages: 160,
    description: 'सूरह अन-नूर की प्रसिद्ध "आयत-ए-नूर" और अंधकार व प्रकाश के आध्यात्मिक रहस्यों का दार्शनिक व रहस्यवादी विवेचन।',
    description_en: 'Esoteric mystical treatise by Al-Ghazali interpreting the famous Light Verse (Ayat al-Nur) and the Hadith of the Veils.',
    downloads_count: 12400,
    views_count: 43200,
    is_featured: false,
    file_name: 'mishkat-al-anwar-ghazali.pdf',
    cover_bg: '#170624',
    cover_color: '#7e22ce',
    accent_color: '#c084fc',
    tag: 'ज्ञान व प्रकाश'
  },
  {
    id: 'thanvi-bayan-al-quran',
    title_en: 'Bayan al-Quran (Scholarly Urdu Commentary)',
    title_ur: 'بیان القرآن',
    title_hi: 'बयान अल-कुरआन (विद्वतापूर्ण उर्दू तफ़्सीर)',
    title_ar: 'بيان القرآن في تفسير كلام الرحمن',
    author_en: 'Maulana Ashraf Ali Thanvi',
    author_ur: 'مولانا اشرف علی تھانوی',
    author_hi: 'मौलाना अशरफ़ अली थानवी',
    author_ar: 'العلامة أشرف علي التهانوي',
    category: 'quran-tafsir',
    era: 'Modern Era (20th Century / 14th AH)',
    hijri_year: '1326 AH',
    year: '1908',
    language: 'Urdu / Arabic / Hindi',
    publisher: 'Matba-e-Mujtabai, Delhi / Maktaba-e-Thanvi',
    pages: 840,
    description: 'उर्दू भाषा में कुरआन की सर्वाधिक प्रामाणिक, सूक्ष्म व्याकरण, तसव्वुफ़ और न्यायशास्त्र से परिपूर्ण शोधपरक तफ़्सीर।',
    description_en: 'Comprehensive scholarly Urdu exegesis noted for its linguistic precision, legal derivations, and spiritual insights.',
    downloads_count: 29500,
    views_count: 112000,
    is_featured: true,
    file_name: 'bayan-al-quran-thanvi.pdf',
    cover_bg: '#1c1303',
    cover_color: '#b45309',
    accent_color: '#fef08a',
    tag: 'कुरआन तफ़्सीर'
  }
];
